namespace: monk-postgresql-cluster

stack:
  defines: process-group
  runnable-list:
    - monk-postgresql-cluster/db1
    - monk-postgresql-cluster/db2
  variables:
    image_tag:
      type: int
      value: 14
    db1_port: 5432
    db2_port: 5433